defaults: &defaults
  docker:
    - image: circleci/node:13.8.0

version: 2.1

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: npm i
      - save_cache:
          key: "npm-packages"
          paths:
            - /src/node_modules
      - run: npm run lint

  test:
    <<: *defaults
    steps:
      - checkout
      - npm i
      - restore_cache:
          keys:
            - "npm-packages"
      - run: npm run test

  analyze:
    <<: *defaults
    steps:
      - checkout
      - npm i
      - restore_cache:
          keys:
            - "npm-packages"
      - run: npm audit

workflows:
  dev-build:
    jobs:
      - build
      - test:
          requires: [build]
      - analyze:
          requires: [test]
